#ifndef STYLE_H
#define STYLE_H

#include <QString>

static const QString night_stylesheet =
        "QTabBar::tab { background: #00374f; color: #ffffd3; padding: 8px; padding-left: 20px;padding-right: 20px;"
            " border: 1px solid #000000; border-style:outset; border-top-left-radius: 4px;border-top-right-radius: 4px;} "
        "QTabBar::tab:selected { background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #0000a3, stop: 1.0 #000043); color: #ffffd3;} "
        "QTabBar::tab:!selected { margin-top: 5px;}"
        "QTabBar::tab:hover:!selected {background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #00008d, stop: 0.4 #00374f, stop: 0.5 #00374f, stop: 1.0 #00008d);}"
        "QWidget#memoryControlsFrame {background: none;}"
        "QWidget#memoriesFrame {background: none;}"
        "QWidget#memoriesTableWidget {background: none;}"
        "QWidget, QTabWidget, QFrame {background-color:#2a2a2a; color:#ffffd3;}"
        "QLabel {border:1px solid #505050;border-radius:4px;background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2c2c2c, stop: 1.0 #272727); color: #ffffd3;}"
        "QPushButton {background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #555555, stop: 0.4 #747474, stop: 0.5 #6a6a6a, stop: 1.0 #555555); color:#ffffd3;"
            "border-radius: 4px;border:1px solid #747474;border-style:outset;margin:2px;padding:5px;}"
        "QPushButton:hover {background-color:#000043; color:#ffffd3;border:1px solid #002c86;}"
        "QPushButton:checked {background-color:#7a7a84; color:#ffffd3;border-style:inset;}"
        "QPushButton:checked:hover {background-color: #7a7a84; border-style:inset;}"
        "QCheckBox:hover {background-color:#555555; color:#ffffd3;}"
        "QCheckBox:checked {color:#fffb6f;}"
        "QDial {background-color:#5a5a5a; color:#ffffd3;}"
        "QDial:hover {background-color:#002c86; color:#ffffd3}"
        "QComboBox {border: 1px solid #002c86; border-style: outset;border-radius: 5px; color: #f0f077; padding: 3px 6px 3px 6px; background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #0000a3, stop: 1.0 #000043);}"
        "QComboBox QAbstractItemView {selection-background-color: lightgray; color: #f0f077; background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #0000a3, stop: 1.0 #000043);}"
        "QComboBox::drop-down {border: 0px solid gray;image:url(\":/res/go-down-arrow.png\");subcontrol-origin: padding;subcontrol-position: right;margin-right:4px;}"
        "QTreeWidgetItem {background-color:#001e5a; color:#ffffd3;}"
        "QTreeWidgetItem:hover {background-color:#002c86; color:#ffffd3}"
        "QLineEdit, QTextEdit {background-color:#a3a3a3; color:#000000;border: 1px solid #dddddd; border-style:inset; border-radius:4px;}"
        "QLineEdit:hover, QTextEdit:hover {border: 2px solid #55aaff; border-radius:4px;}"
        "QLineEdit:focus, QTextEdit:focus {border: 2px solid #2277ff;border-radius:4px;}"
        "QSlider::sub-page:vertical {border: 1px solid #bbb;"
            "background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #000043, stop: 1.0 #0000a3);"
            "border: 1px solid #777;border-style:outset;height: 5px;border-radius: 3px;}"
        "QSlider::sub-page:horizontal {border: 1px solid #bbb;"
            "background-color: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #000043, stop: 1.0 #0000a3);"
            "border: 1px solid #777;border-style:outset;height: 5px;border-radius: 3px;}"
        "QSlider::add-page {"
            "background-color: #f0f077;border: 1px solid #777;border-style:inset;height: 5px;border-radius: 3px;}"
        "QSlider::handle {"
            "background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1,"
            " stop:0 #eee, stop:1 #ccc);"
            "border: 1px solid #777;width: 16px;border-radius: 4px;}"
        "QSlider::handle:hover {"
            "background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1,"
            " stop:0 #fff, stop:1 #ddd);"
            "border: 1px solid #444;border-radius: 4px;}"
        "QSlider::sub-page:disabled {background-color: #bbb;border-color: #999;}"
        "QSlider::add-page:disabled {background-color: #eee;border-color: #999;}"
        "QSlider::handle:disabled {background-color: #eee;border: 1px solid #aaa;border-radius: 4px;};";


static const QString day_stylesheet =
        "QTabBar::tab { background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #bebebe, stop: 0.3 #dfdfdf, stop: 0.7 #c7c7c7, stop: 1.0 #bebebe); color: #000000; padding: 8px; padding-left: 20px;padding-right: 20px;"
            "border: 1px solid #aaaaaa; border-style:outset; border-top-left-radius: 5px;border-top-right-radius: 5px;} "
        "QTabBar::tab:selected { background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #fafafa, stop: 0.4 #f4f4f4, stop: 0.5 #e7e7e7, stop: 1.0 #fafafa); color: #000000; } "
        "QTabBar::tab:!selected { margin-top: 5px;}"
        "QTabBar::tab:hover:!selected {background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #fafafa, stop: 0.4 #f4f4f4, stop: 0.5 #e7e7e7, stop: 1.0 #fafafa);}"
        "QWidget#memoryControlsFrame {background: none}"
        "QWidget#memoriesFrame {background: none;}"
        "QWidget#memoriesTableWidget {background: none}"
        "QWidget, QTabWidget {background-color:#cccccc; color:#000000}"
        "QFrame {background-color:#cccccc; color:#000000}"
        "QLabel {border:1px solid darkgrey;border-radius:4px;background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #c3c3c3, stop: 1.0 #b8b8b8); color: #232323;}"
        "QPushButton {margin:2px;background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #bebebe, stop: 0.4 #dfdfdf, stop: 0.5 #c7c7c7, stop: 1.0 #bebebe);padding:5px; border: 1px solid gray; border-style: outset; border-radius:4px;}"
        "QPushButton:checked {background-color: #b9b9b9; border-style:inset;}"
        "QPushButton:checked:hover {background-color: #b9b9b9; border-style:inset;}"
        "QPushButton:hover {margin:2px;background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #fafafa, stop: 0.4 #f4f4f4, stop: 0.5 #e7e7e7, stop: 1.0 #fafafa); border: 1px solid gray; border-style: outset; border-radius:4px;}"
        "QCheckBox:hover {background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #fafafa, stop: 0.4 #f4f4f4, stop: 0.5 #e7e7e7, stop: 1.0 #fafafa);}"
        "QCheckBox:checked {color:#585800}"
        "QDial {background-color:#9a9a9a; color:#ffffd3;border:0px solid black;}"
        "QDial:hover {background-color:#002c86; color:#ffffd3}"
        "QComboBox {border: 1px solid #002c86; border-style: outset;border-radius: 6px; color: #f0f077; padding: 3px 6px 3px 6px; background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #0000a3, stop: 1.0 #000043);}"
        "QComboBox QAbstractItemView {border:1px solid grey;selection-background-color: lightgray; color: #f0f077; background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #0000a3, stop: 1.0 #000043);}"
        "QComboBox::drop-down {border: 0px solid gray;image:url(\":/res/go-down-arrow.png\");subcontrol-origin: padding;subcontrol-position: right;margin-right:4px;}"
        "QTreeWidgetItem {background-color:#2a2a2a; color:#ffffd3}"
        "QTreeWidget {background-color:#2a2a2a; color:#ffffd3}"
        "QTreeWidgetItem:hover {background-color:#002c86; color:#ffffd3}"
        "QLineEdit, QTextEdit {background-color:#f0f0f0; color:#000000;border: 1px solid #dddddd; border-style:inset; border-radius:4px;}"
        "QLineEdit:hover, QTextEdit:hover {background-color:#f0f0f0; color:#000000;border: 2px solid #55aaff; border-radius:4px;}"
        "QLineEdit:focus, QTextEdit:focus {border: 2px solid #2277ff;border-radius:4px;}"
        "QSlider::sub-page:vertical {border: 1px solid #bbb;"
            "background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #000043, stop: 1.0 #0000a3);"
            "border: 1px solid #777;border-style:outset;height: 5px;border-radius: 3px;}"
        "QSlider::sub-page:horizontal {border: 1px solid #bbb;"
            "background-color: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #000043, stop: 1.0 #0000a3);"
            "border: 1px solid #777;border-style:outset;height: 5px;border-radius: 3px;}"
        "QSlider::add-page {border: 1px solid #bbb;"
            "background-color: #ffffd3;border: 1px solid #777;border-style:inset;height: 5px;border-radius: 3px;}"
        "QSlider::handle {"
            "background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1,"
            " stop:0 #eee, stop:1 #ccc);"
            "border: 1px solid #777;width: 6px;height:6px;border-radius: 4px;}"
        "QSlider::handle:hover {"
            "background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1,"
            " stop:0 #fff, stop:1 #ddd);"
            "border: 1px solid #444;border-radius: 4px;}"
        "QSlider::sub-page:disabled {background-color: #bbb;border-color: #999;}"
        "QSlider::add-page:disabled {background-color: #eee;border-color: #999;}"
        "QSlider::handle:disabled {background-color: #eee;border: 1px solid #aaa;border-radius: 4px;};";

#endif // STYLE_H
