.TH QRADIOLINK "1" "July 2021" "qradiolink" "User Commands"
.SH NAME
qradiolink \- Qt GUI SDR and VOIP transceiver application
.SH DESCRIPTION
QRadioLink is a VOIP (radio over IP) GNU/Linux SDR (software defined radio) transceiver application using Internet protocols for communication,
built on top of [GNU radio](https://www.gnuradio.org/), 
which allows experimenting with software defined radio hardware using different digital and analog radio signals and a Qt5 user interface.
.PP
Its primary purpose is educational, but it can also be customized for low power data communications on various ISM frequency bands.
It can also be used as a low power amateur radio SDR transceiver for demonstrating radio communications to children at schools.
.PP
The application was originally inspired from the [Codec2 GMSK modem](https://github.com/on1arf/gmsk) project by Kristoff Bonne.
.SH FEATURES
.PP
VOIP (Radio-over-IP) connection between two or more stations operating in simplex or semi-duplex mode
.PP
Radio forwarding over VOIP - forward voice to the VOIP connection and viceversa
.PP
Direct VOIP talk-around (only requires connection to a VOIP server and no radio)
.PP
Wideband audio streaming over the Internet with the **Opus** audio codec
.PP
Configurable VOIP bitrate
.PP
Audio recording for local audio output in FLAC format
.PP
Remote control via network (requires a telnet client or similar program, can be scripted)
.PP
Remote control via Mumble private text messages
.PP
Run headless (no graphical user interface) for terminal usage on embedded platforms like the Raspberry Pi or similar boards without any screen
.PP
Night mode theme
.PP
Transmit and receive analog FM, SSB, AM, digital voice, text messages, digital video, IP protocol.
.PP
Mixed operation mode (receive one mode and transmit another)
.PP
Full duplex and simplex operation
.PP
Fast tune reverse repeater shift using dedicated button
.PP
Memory channels (store frequency, name, TX shift, operating mode, squelch value, volume, TX power, RX gain, TX and RX CTCSS) and memory channel scan 
.PP
Split operation (transmit on other frequency than the receive frequency with no shift limitation, used mostly for repeater operation)
.PP
Digital voice codecs: Codec2 700 bit/s, Codec2 1400 bit/s, Opus 9600 bit/s
.PP
M17 digital voice modulator and demodulator (currently supports only voice streaming)
.PP
FreeDV digital voice modulator and demodulator (currently supports only 1600, 700C `and 800XA modes)
.PP
MMDVM base station mode with TDMA support (DMR, System Fusion, D-Star, M17) using LimeSDR devices
.PP
Multi-channel / multi-carrier MMDVM system using LimeSDR devices
.PP
Digital modulations: **FreeDV 1600**, **FreeDV 700C**, **FreeDV 800XA**, **BPSK**, **DQPSK**, **2FSK**, **4FSK**, **M17**
.PP
Digital voice modem bitrates over the air from 1 kbit/s to 10 kbit/s
.PP
Video bitrate below 250 kbit/s at 10 frames/second with sound using the Opus codec at 9400 kbit/s
.PP
Analog modulations: FM (12.5 kHz), narrow FM (6.25 kHz), SSB, AM, Wide FM (broadcast, receive-only)
.PP
Configurable filter widths for analog modes
.PP
CTCSS encoder and decoder for analog FM
.PP
VOX mode
.PP
Analog and digital mode repeater - in full duplex mode only, same mode or mixed mode repeater (e.g. FM to Codec2 and viceversa, or FM to Opus and viceversa)
.PP
Repeater linking via VOIP and Mumble - a group of repeaters can be linked duplex by sharing the same Mumble channel. This feature is still experimental and WIP.
.PP
Internal audio mixing of audio from VOIP server and audio from radio
.PP
USB FTDI (FT232) relay control support (for RF switches, power amplifier and filter control). Boards with up to 8 relays are supported.
.PP
Full duplex DQPSK 250 kbit/s and 4FSK 96 kbit/s IP radio modems with configurable TX/RX offsets
.PP
Automatic carrier tracking and Doppler effect correction for all digital modes except FreeDV modes. The system can track Doppler shifts of 5-10 kHz, depending on mode. It requires a CNR of at least 10-12 dB, more for FSK modes than for PSK modes. 
.PP
Experimental GPredict radio control integration.
.SH "SEE ALSO"
The full documentation for qradiolink is installed
in /usr/share/doc/qradiolink
