#ifndef MAPGRAPHICS_GLOBAL_H
#define MAPGRAPHICS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MAPGRAPHICS_LIBRARY)
#  define MAPGRAPHICSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MAPGRAPHICSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MAPGRAPHICS_GLOBAL_H
