#ifndef MODEM_TYPES_H
#define MODEM_TYPES_H

namespace gr_modem_types {
    enum
    {
        ModemTypeBPSK2K,
        ModemTypeQPSK20K,
        ModemTypeQPSKVideo,
        ModemType4FSK2K,
        ModemType4FSK10KFM,
        ModemType4FSK2KFM,
        ModemType4FSK1KFM,
        ModemTypeQPSK2K,
        ModemTypeNBFM2500,
        ModemTypeNBFM5000,
        ModemTypeWBFM,
        ModemTypeUSB2500,
        ModemTypeLSB2500,
        ModemTypeCW600USB,
        ModemTypeAM5000,
        ModemType2FSK2KFM,
        ModemType2FSK1KFM,
        ModemType2FSK2K,
        ModemType2FSK1K,
        ModemType2FSK10KFM,
        ModemTypeGMSK2K,
        ModemTypeGMSK1K,
        ModemTypeGMSK10K,
        ModemType2FSK10KFMINET,
        ModemTypeBPSK1K,
        ModemTypeBPSK8,
        ModemTypeQPSK250K,
        ModemType4FSK100K,
        ModemTypeFREEDV1600USB,
        ModemTypeFREEDV700CUSB,
        ModemTypeFREEDV700DUSB,
        ModemTypeFREEDV800XAUSB,
        ModemTypeFREEDV2400AUSB,
        ModemTypeFREEDV1600LSB,
        ModemTypeFREEDV700CLSB,
        ModemTypeFREEDV700DLSB,
        ModemTypeFREEDV800XALSB,
        ModemTypeFREEDV2400ALSB,
        ModemTypeMMDVM,
        ModemTypeMMDVMmulti,
        ModemTypeM17,
        ModemTypeDMR,
    };
}

namespace OperationMode {
    enum
    {
        ModeFM = 0,
        ModeNBFM = 1,
        ModeWBFM = 2,
        ModeUSB = 3,
        ModeLSB = 4,
        ModeFreeDV1600USB = 5,
        ModeFreeDV700CUSB = 6,
        ModeFreeDV700DUSB = 7,
        ModeFreeDV800XAUSB = 8,
        ModeFreeDV1600LSB = 9,
        ModeFreeDV700CLSB = 10,
        ModeFreeDV700DLSB = 11,
        ModeFreeDV800XALSB = 12,
        ModeAM = 13,
        ModeBPSK2K = 14,
        ModeBPSK1K = 15,
        ModeQPSK2K = 16,
        ModeQPSK10K = 17,
        Mode2FSK2KFM = 18,
        Mode2FSK1KFM = 19,
        Mode2FSK2K = 20,
        Mode2FSK1K = 21,
        Mode2FSK10KFM = 22,
        ModeGMSK2K = 23,
        ModeGMSK1K = 24,
        ModeGMSK10K = 25,
        Mode4FSK2K = 26,
        Mode4FSK2KFM = 27,
        Mode4FSK1KFM = 28,
        Mode4FSK10KFM = 29,
        ModeQPSKVideo = 30,
        ModeQPSK250K = 31,
        Mode4FSK100K = 32,
        ModeMMDVM = 33,
        ModeMMDVMMulti = 34,
        ModeM17 = 35,
        ModeDMR = 36,
    };
}



#endif // MODEM_TYPES_H
